// Generated by the SS6 Developer agent. DB access via a repository (context.md §4).
import { RowDataPacket } from 'mysql2/promise';
import { query } from '../db/pool';
import { TopCustomerRow } from '../services/analytics';

export async function topCustomersBySpend(limit = 10): Promise<TopCustomerRow[]> {
  const n = Math.max(1, Math.min(100, Math.trunc(limit)));
  return query<(TopCustomerRow & RowDataPacket)[]>(
    `SELECT c.id AS customer_id, c.full_name, c.loyalty_tier,
            COALESCE(SUM(CASE WHEN o.status <> 'cancelled' THEN o.total_satang ELSE 0 END), 0) AS spend_satang
       FROM customers c
       LEFT JOIN orders o ON o.customer_id = c.id
      GROUP BY c.id, c.full_name, c.loyalty_tier
      ORDER BY spend_satang DESC
      LIMIT ${n}`,
  );
}
