// Generated by the SS6 Developer agent (Top Customers by Spend).
// Business logic lives in a service (context.md §4); pure + unit-tested.
export interface TopCustomerRow {
  customer_id: number;
  full_name: string;
  loyalty_tier: string;
  spend_satang: number;
}

/** Pure: rank customers by spend (descending) and take the top N. */
export function rankCustomersBySpend(rows: TopCustomerRow[], limit = 10): TopCustomerRow[] {
  const n = Math.max(0, Math.trunc(limit));
  return [...rows].sort((a, b) => b.spend_satang - a.spend_satang).slice(0, n);
}
