// Generated by the SS6 Developer agent. Thin controller; logic stays in services.
import { Request, Response, NextFunction } from 'express';
import * as analyticsRepo from '../repositories/analyticsRepository';
import { rankCustomersBySpend } from '../services/analytics';

export async function getTopCustomers(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const limit = req.query.limit ? Number(req.query.limit) : 10;
    const rows = await analyticsRepo.topCustomersBySpend(limit);
    res.json({ topCustomers: rankCustomersBySpend(rows, limit) });
  } catch (err) {
    next(err);
  }
}
