#!/usr/bin/env bash
# ss6_demo.sh — close the loop, $0, end to end:
#   requirement -> SS6 generates a multi-file feature -> REAL tsc + jest gate
#   -> apply to target_repo -> rebuild the API -> curl the new live endpoint
#   -> open a DRAFT GitHub PR.  Nothing is auto-merged.
#
# Usage:  bash scripts/ss6_demo.sh "Add a Top Customers by Spend analytics endpoint"
set -euo pipefail

REQ="${1:-Add a Top Customers by Spend analytics endpoint}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="$ROOT/target_repo"
DOCKER="${DOCKER:-docker}"            # override if docker isn't on PATH
OUT="$ROOT/out"
export SS6_LLM_PROVIDER="${SS6_LLM_PROVIDER:-mock}"   # $0: deterministic, no API key
export SS6_EXEC_DIR="${SS6_EXEC_DIR:-$ROOT/out/exec}"

say(){ printf "\n\033[1;32m== %s\033[0m\n" "$*"; }

say "1/6  SS6 plans + generates the feature, with the REAL tsc+jest gate"
# Reuse target_repo/backend/node_modules so the gate is fast (install once if absent).
[ -d "$REPO/backend/node_modules" ] || (cd "$REPO/backend" && npm install --no-audit --no-fund)
ss6 run "$REQ" --out "$OUT" --run-tests

WORKDIR="$(ls -dt "$SS6_EXEC_DIR"/*/repo | head -1)"
say "2/6  Generated change (in the isolated copy: $WORKDIR)"
git -C "$WORKDIR" --no-pager diff --stat main || true

say "3/6  Apply the generated files into target_repo"
( cd "$WORKDIR" && git diff --name-only main ) | while read -r f; do
  mkdir -p "$REPO/$(dirname "$f")"
  cp "$WORKDIR/$f" "$REPO/$f"
done

say "4/6  Rebuild + restart the API container"
( cd "$REPO" && $DOCKER compose up -d --build api )
for i in $(seq 1 20); do curl -fs http://localhost:4000/api/v1/health >/dev/null 2>&1 && break; sleep 2; done

say "5/6  Curl the NEW live endpoint (data straight from MySQL)"
curl -s "http://localhost:4000/api/v1/dashboard/top-customers?limit=5" | python3 -m json.tool

say "6/6  Open a DRAFT pull request (nothing merged)"
BR="ss6/top-customers-by-spend"
git -C "$ROOT" checkout -b "$BR" 2>/dev/null || git -C "$ROOT" checkout "$BR"
git -C "$ROOT" add -A
git -C "$ROOT" commit -q -m "feat(eleven-7): Top Customers by Spend endpoint (generated by SS6, gate: tsc+jest+compliance)" || true
git -C "$ROOT" push -u origin "$BR" 2>/dev/null || git -C "$ROOT" push origin "$BR"
gh pr create --draft --title "feat: Top Customers by Spend (SS6-generated)" \
  --body "Generated by the SS6 pipeline from the requirement: \"$REQ\". Gate: context.md compliance + real tsc + jest. Halted for human review." \
  2>/dev/null || echo "(open the PR manually if gh prompts)"

say "Done — requirement → verified, running feature → draft PR. \$0, fully local."
